Accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from Accounts.forms import SignInForm, ForgotPasswordForm, NewPasswordForm, ChangePasswordForm
from django.urls import reverse_lazy

#Namespace for the Accounts app.
app_name = 'Accounts'

urlpatterns = [
    #A url mapped to a view that generates an email confirmation request.
    path('email_confirmation/<uidb64>/<token>/',views.email_confirmation, name='email_confirmation'),
    #A url mapped to a view that renders the user's my account page.
    path('myaccount/', views.myaccount, name = 'myaccount'),
    #A url mapped to a view that renders a password change page for signed in users.
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='Accounts/password_change_form.html', form_class=ChangePasswordForm, success_url=reverse_lazy('Accounts:password_change_done')), name='password_change'),
    #A url mapped to a view that generates a response when a signed in user changes their password.
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='Accounts/password_change_done.html'), name='password_change_done'),
    #A url mapped to a view that renders the reset password page.
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='Accounts/password_reset.html', success_url=reverse_lazy('Accounts:password_reset_done'),form_class=ForgotPasswordForm, email_template_name='Accounts/password_reset_email.html', subject_template_name='Accounts/password_reset_subject.txt'), name='password_reset'),
    #A url mapped to a view that renders a response on a user's request to reset their password on the reset password page.
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Accounts/password_reset_done.html'), name='password_reset_done'),
    #A url mapped to a view that generates a reset password link that is emailed to the user's email address.
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Accounts/password_reset_confirm.html", form_class=NewPasswordForm, success_url=reverse_lazy('Accounts:password_reset_complete')), name='password_reset_confirm'),
    #A url mapped to a view that renders a message when the user opens the reset password link.
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='Accounts/password_reset_complete.html'), name='password_reset_complete'),
    #A url mapped to a view that renders the signin page.
    path('signin/', auth_views.LoginView.as_view(template_name='Accounts/signin.html', authentication_form=SignInForm, redirect_field_name="Notes/my_diaries.html"), name = 'login'),
    #A url mapped to a view that handles a user signout.
    path('signout/', auth_views.LogoutView.as_view(), name = 'logout'),
    #A url mapped to a view that renders the signup page.
    path('signup/', views.signup, name = 'signup'),
    #A url mapped to a view that renders a response when a user confirms their email address.
    path('signup/complete/',views.SignUpCompleteView.as_view(), name='signup_complete'),
    #A url mapped to a view that renders a response when a user signs up.
    path('signup/done/',views.SignUpDoneView.as_view(), name='signup_done'),
    #A url mapped to a view that renders a forgot username page.
    path('username_send/', views.send_username, name='send_username'),
    #A url mapped to a view that renders a response when a user's username is emailed to their email address.
    path('username_send_done/',views.SendUsernameDoneView.as_view(), name='send_username_done'),
]

Cart/urls.py
from Cart import views
from django.urls import path

#Namespace for the Cart app.
app_name = "Cart"

urlpatterns = [
    #A URL mapped to CartPageView view that renders a user's cart on the cart page.
    path('cart/', views.CartPageView.as_view(), name='cart_page'),
    #A URL mapped to CartAddView view that adds a product to a user's cart.
    path('cart/add/<pk>/', views.CartAddView.as_view(), name='add_to_cart'),
    #A URL mapped to CartRemoveView view that removes a product from a user's cart.
    path('cart/remove/<pk>', views.CartRemoveView.as_view(), name='remove_from_cart'),
]

SplendidReads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #The admin site URL.
    path('admin/', admin.site.urls),
    #Includes the 'Products' app URLs.
    path('',include('Products.urls')),
    #Includes the 'Accounts' app URLs.
    path('',include('Accounts.urls')),
    #Includes the 'Cart' app URLs.
    path('',include('Cart.urls')),
    #Includes the 'Payments' app URLs.
    path('',include('Payments.urls')),
    #Includes the 'Ebooks' app URLs.
    path('',include('Ebooks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models

# Create your models here.

Accounts/views.py
from Accounts.forms import SignUpForm, SignInForm, ForgotUserNameForm, UpdateUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db import transaction
from django.db.models import Q
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView

class SendUsernameDoneView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render a response to the user on emailing them their username.

    Attributes
    ----------
    template_name : str
        The html page for the user response.
    """
    template_name = "Accounts/username_send_done.html"


class SignUpCompleteView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render a response to the user on confirming their email after signing up.

    Attributes
    ----------
    template_name : str
        The html page for the user response.
    """
    template_name = "Accounts/signup_complete.html"


class SignUpDoneView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render a response to the user on signing up.

    Attributes
    ----------
    template_name : str
        The html page for the user response.
    """
    template_name = "Accounts/signup_done.html"


def signup(request):
    """
    A view that:
        renders the signup page.
        Validates the SignUpForm data.
        Creates a new User object with 'is_active' status as 'False' if the SignUpForm POST data is valid.
        Sends an email confirmation email to a newly created user.
        An activation link is created by using:
            The desired protocol.
            the current domain name.
            a base64 encoded unique user id.
            Django's default token generator.
        A user cannot sign in until the email is not confirmed.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.

    Returns
    -------
    HttpResponseRedirect
        A request to the signup_done page when the user submits valid POST data and a new User object is created.
    HttpResponse
        A new SignUpForm instance when the user accesses the signup page.
        A SignUpForm instance with errors when the user enters invalid data.

    Raises
    ------
    ValidationError
        If the form data is not correct or as per guidelines.
    """
    if request.method == "POST":
        form = SignUpForm(request.POST)
        i_agree = request.POST.get("i_agree", False)
        if form.is_valid() and i_agree:
            with transaction.atomic():
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Confirm your email.'
                message = render_to_string('Accounts/new_account_activation_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                    'token':default_token_generator.make_token(user),
                    'protocol': 'https',
                })
                email_id = form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[email_id])
                email.send()
            return redirect('Accounts:signup_done')
        return render(request, 'Accounts/signup.html', {'form':form, 'i_agree':i_agree})
    else:
        form = SignUpForm()
        return render(request, 'Accounts/signup.html', {'form':form})


@login_required
def myaccount(request):
    """
    A view that renders the personal details of an authenticated user.
    This view can be accesssed on if a user is authenticated or is signed in.
    It cannot be accessed by anonymous users.
    the login_required decorator ensures that this view can be only accessed by signed in users.
    Anonymous users are redirected to the signin page.
    The view populates a UpdateUserForm once rendered.
    The user is free to change name credentials and username which are updated in the database.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.

    Returns
    -------
    HttpResponseRedirect
        A request to the same view when the user submits valid POST data and a the User object is updated.
    HttpResponse
        A user accesses the personal details page to view their information.

    Raises
    ------
    ValidationError
        If the form data is not correct or as per guidelines.
    """
    if request.method == "POST":
        form=UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('Accounts:myaccount')
    form = UpdateUserForm(instance=request.user)
    return render(request, 'Accounts/myaccount.html',{'form': form})


def email_confirmation(request, uidb64, token):
    """
    This view validates an email confirmation link when accessed by a user.
    The base64 encoded unique id is decoded and the token validity is checked.
    If both items are valid, then the user's 'is_active' status is set to 'True'.
    If one or both the data items is invalid, an error message is rendered.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.
    uidb64 : str
        The base64 encoded value of a user's unique id.
    token : str
        A token used for generating the one time email confirmation link.

    Returns
    -------
    HttpResponseRedirect
        A request to the SignUpCompleteView when the user accesses the email confirmation message.
    HttpResponse
        A response indicating an invalid link.

    Raises
    ------
    TypeError
    ValueError
    OverflowError
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('Accounts:signup_complete')
    else:
        message = "Confirmation link is invalid!"
        return render(request, 'Accounts/signup_complete.html', {'message':message})


def send_username(request):
    """
    A view that sends an email to a user if they forget their username_send.
    An email is sent to a registered email address that the user enters after validation.
    A response message is rendered irrespective of whether the email is sent or not. This
    is done in order to avoid exposure of user data.

    Parameters
    ----------
    request : HttpRequest
        An HttpRequest object that contains metadata about a request.

    Returns
    -------
    HttpResponseRedirect
        A request to the SendUsernameDoneView when the user submits valid POST data and a email is sent to the user with their username.
    HttpResponse
        A user accesses the forgot username page.

    Raises
    ------
    ValidationError
        If the form data is not correct or as per guidelines.
    """
    if request.method == "POST":
        form = ForgotUserNameForm(request.POST)
        if form.is_valid():
            mail_subject = 'Account username request.'
            email_id = form.cleaned_data.get("email")
            users = User.objects.filter(email=email_id)
            if users.exists():
                user = users[0]
                message = render_to_string('Accounts/username_send_email.html', {
                    'user': user
                })
                email = EmailMessage(mail_subject, message, to=[email_id])
                email.send()

            return redirect('Accounts:send_username_done')
        return render(request, 'Accounts/username_send_form.html', {'form':form})
    else:
        form = ForgotUserNameForm()
        return render(request, 'Accounts/username_send_form.html', {'form':form})

Accounts/templates/Accounts/myaccount.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
       <div class = "row justify-content-center mt-2">
          <ul class="nav nav-tabs">
              <li class="nav-item">
                  <a href="#personalInfo" class="nav-link active" data-toggle="tab">Personal Info</a>
              </li>
              <li class="nav-item">
                  <a href="#security" class="nav-link" data-toggle="tab">Security</a>
              </li>
          </ul>
       </div>
       <div class="row justify-content-center mt-2">
           <div class="col-xl-8">
              <div class="tab-content">
                  <div class="tab-pane fade show active" id="personalInfo">
                      <div class="card">
                          <div class="card-header text-center form-background-color">
                              <h1 class="text-white">Personal Info<h1>
                          </div>
                          <div class="card-body form-background-color text-white">
                              <form action="{% url 'Accounts:myaccount' %}" method="POST" novalidate>
                              {% csrf_token %}
                                  <div class="form-group">
                                      {{form.first_name.label_tag}}
                                      {{form.first_name}}
                                      <small>{{form.first_name.errors}}</small>
                                  </div>
                                  <div class="form-group">
                                      {{form.last_name.label_tag}}
                                      {{form.last_name}}
                                      <small>{{form.last_name.errors}}</small>
                                  </div>
                                  <div class="form-group">
                                      {{form.username.label_tag}}
                                      {{form.username}}
                                      <small>{{form.last_name.errors}}</small>
                                  </div>
                                  <div class="form-group text-center">
                                      <button type="submit" class="btn btn-orange">Save Changes</button>
                                  </div>
                              </form>
                          </div>
                      </div>
                  </div>
                  <div class="tab-pane fade" id="security">
                      <div class="row justify-content-center align-items-center mt-2">
                          <div class="col-xl-8">
                              <div class="card">
                                  <div class="card-body form-background-color text-center">
                                      <a class="btn btn-orange" href="{% url 'Accounts:password_change' %}" role="button">Change Password</a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/new_account_activation_email.html
{% autoescape off %}

Hi {{ user.get_short_name }},

If you tried to sign up:
You are just a click away from joining the SplendidReads community.
Your username is : {{user.get_username}}

If you did not try to sign up:
Please ignore this email.

Please click on the link below to confirm your registration.

{{ protocol }}://{{ domain }}{% url 'Accounts:email_confirmation' uidb64=uid token=token %}

Sincerely.
The SplendidReads Team

{% endautoescape %}

Accounts/templates/Accounts/password_change_done.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col">
                <p>Congratulations!!!</p>
                <p>Your account password has been successfully changed.</p>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/password_change_form.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col-xl-4">
                <div class="card">
                    <div class="card-header form-background-color">
                        <h2 class = "text-center text-white">Change Password</h2>
                    </div>
                    <div class="card-body form-background-color">
                        <form method="POST" novalidate>
                        {% csrf_token %}
                            <div class="form-group">
                                {{ form.old_password }}
                                <small class="text-danger">{{ form.errors.old_password|striptags}}</small>
                                <small class="text-danger">{{ form.old_password.help_text|striptags}}</small>
                            </div>
                            <div class="form-group">
                                {{ form.new_password1 }}
                                <small class="text-danger">{{ form.errors.new_password1|striptags}}</small>
                                <small class="text-white">{{ form.new_password1.help_text}}</small>
                            </div>
                            <div class="form-group">
                                {{ form.new_password2 }}
                                <small class="text-danger">{{ form.errors.new_password2|striptags}}</small>
                                <small class="text-white">{{ form.new_password2.help_text}}</small>
                            </div>
                            <div class = "form-group text-center">
                                <button type="submit" class="btn btn-orange btn-block">Reset Password</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col-xl-4">
                <div class="card">
                    <div class="card-header form-background-color">
                        <h2 class = "text-center text-white">Reset Password</h2>
                    </div>
                    <div class="card-body form-background-color">
                        <form method="POST" novalidate>
                        {% csrf_token %}
                            <div class="form-group">
                                {{ form.email }}
                                <small class="text-danger">{{ form.errors.email|striptags}}</small>
                            </div>
                            <div class = "form-group text-center">
                                <button type="submit" class="btn btn-orange btn-block">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        {% if validlink %}
            <div class = "row justify-content-center align-items-center">
                <div class = "col-xl-4">
                    <div class="card">
                        <div class="card-header form-background-color">
                            <h2 class = "text-center text-white">Reset Password</h2>
                        </div>
                        <div class="card-body form-background-color">
                            <form method="POST" novalidate>
                            {% csrf_token %}
                                <div class="form-group">
                                    {{ form.new_password1 }}
                                    <small class="text-danger">{{ form.errors.new_password1|striptags}}</small>
                                    <small class="text-white">{{ form.new_password1.help_text }}</small>
                                </div>
                                <div class="form-group">
                                    {{ form.new_password2 }}
                                    <small class="text-danger">{{ form.errors.new_password2|striptags}}</small>
                                </div>
                                <div class = "form-group text-center">
                                    <button type="submit" class="btn btn-orange btn-block">Reset Password</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="row">
                <p>
                    The password reset link is invalid, possibly because it has already been used.
                    Please request for a new password reset.
                </p>
            </div>
        {% endif %}
    </div>
{% endblock %}

Accounts/templates/Accounts/signin.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col-xl-4">
                <div class="card">
                    <div class="card-header form-background-color">
                        <h2 class="text-center text-white">Sign In</h2>
                    </div>
                    {% if messages %}
                        <div class="messages text-center bg-danger">
                            {% for message in messages %}
                            <p{% if message.tags %} class="{{ message.tags }} text-white"{% endif %}>{{ message }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if form.errors %}
                        <div class="bg-danger text-white text-center">
                            <p>Username or password is invalid.</p>
                        </div>
                    {% endif %}
                    <div class="card-body form-background-color">
                        <form method="POST" novalidate>
                        {% csrf_token %}
                            <div class="form-group">
                                {{ form.username }}
                                 <small class="text-danger">{{ form.errors.username|striptags}}</small>
                            </div>
                            <div class="form-group">
                                {{ form.password }}
                                 <small class="text-danger">{{ form.errors.password|striptags}}</small>
                            </div>
                            <div class = "form-group text-center">
                                <button type="submit" class="btn btn-orange btn-block">Submit</button>
                            </div>
                            <div class = "text-center">
                                <a href = "{% url 'Accounts:password_reset' %}"><small>Forgot Password?</small></a>
                            </div>
                            <div class = "text-center">
                                <a href = "{% url 'Accounts:send_username' %}"><small>Forgot Username?</small></a>
                            </div>
                            <div class = "text-center">
                                <label class="text-white"><small>Not using SplendidReads yet? <a href = "{% url 'Accounts:signup' %}">Sign Up</a></small></label>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col-xl-4">
                <div class="card">
                    <div class="card-header form-background-color">
                        <h2 class = "text-center text-white">Sign Up</h2>
                    </div>
                    <div class="card-body form-background-color">
                        <form action="{% url 'Accounts:signup' %}" method="post" novalidate>
                        {% csrf_token %}
                            <div class = "row">
                                <div class = "col-md-6">
                                    <div class="form-group">
                                        {{ form.first_name }}
                                        <small class="text-danger">{{ form.errors.first_name|striptags}}</small>
                                    </div>
                                </div>
                                <div class = "col-md-6">
                                    <div class="form-group">
                                        {{ form.last_name }}
                                        <small class="text-danger">{{ form.errors.last_name|striptags}}</small>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form.username }}
                                <small class="text-white">{{form.username.help_text}}</small>
                                <small class="text-danger">{{ form.errors.username|striptags}}</small>
                            </div>
                            <div class="form-group">
                                {{ form.email }}
                                <small class="text-danger">{{ form.errors.email|striptags}}</small>
                            </div>
                            <div class="form-group">
                                {{ form.password1 }}
                                <small class="text-white">{{form.password1.help_text}}</small>
                                <small class="text-danger">{{ form.errors.password1|striptags}}</small>
                            </div>
                            <div class="form-group">
                                {{ form.password2 }}
                                <small class="text-white">{{form.password2.help_text}}</small>
                                <small class="text-danger">{{ form.errors.password2|striptags}}</small>
                            </div>
                            <div class="form-group custom-control custom-switch">
                                <input type="checkbox" class="custom-control-input" name = "i_agree" id="i_agree" required>
                                <label class = "custom-control-label text-white" for = "i_agree"><small>I agree to SplendidReads's <a href = "">Terms of Service</a> and <a href = ""> Privacy Policy</a></small></label>
                                {% if i_agree is False %}
                                <small class="text-danger">This is required</small>
                                {% endif %}
                            </div>
                            <div class = "form-group text-center">
                                <button type="submit" class="btn btn-orange btn-block">Sign Up</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/signup_complete.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col">
            {% if message %}
                {{ message }}
            {% endif %}
            {% if not message %}
                <p>Welcome to the community.</p>
                <p>Thank you for being a part of SplendidReads.</p>
                <p>Thank you for confirming your email. You may now <a href="{% url 'Accounts:login' %}">Sign In</a>.</p>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/signup_done.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col">
                <p>You are just a step away from joining the <strong>SplendidReads</strong> community!!!</p>
                <p> We have emailed you an email confirmation link to the email address you used to register with us.
            </div>
        </div>
    </div>
{% endblock %}

Accounts/templates/Accounts/username_send_form.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-5">
        <div class = "row justify-content-center align-items-center">
            <div class = "col-xl-4">
                <div class="card">
                    <div class="card-header form-background-color">
                        <h2 class = "text-center text-white">Forgot Username</h2>
                    </div>
                    <div class="card-body form-background-color">
                        <form action="{% url 'Accounts:send_username' %}" method="POST"  novalidate>
                        {% csrf_token %}
                            <div class="form-group">
                                {{ form.email }}
                                <small class="text-danger">{{ form.errors.email|striptags }}</small>
                            </div>
                            <div class = "form-group text-center">
                                <button type="submit" class="form-control btn btn-orange btn-block">Send Username</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}