Cart/urls.py
from Cart import views
from django.urls import path

#Namespace for the Cart app.
app_name = "Cart"

urlpatterns = [
    #A URL mapped to CartPageView view that renders a user's cart on the cart page.
    path('cart/', views.CartPageView.as_view(), name='cart_page'),
    #A URL mapped to CartAddView view that adds a product to a user's cart.
    path('cart/add/<pk>/', views.CartAddView.as_view(), name='add_to_cart'),
    #A URL mapped to CartRemoveView view that removes a product from a user's cart.
    path('cart/remove/<pk>', views.CartRemoveView.as_view(), name='remove_from_cart'),
]

Ebooks/urls.py
from django.urls import path
from Ebooks import views

#Namespace for the Ebooks app.
app_name = "Ebooks"

urlpatterns = [
    #A URL mapped to the MyEbooksView that renders a user's ebooks.
    path('myebooks/', views.MyEbooksView.as_view(), name='my_ebooks'),
]

Payments/urls.py
from django.urls import path
from Payments import views

#Namespace for the 'Payments' app.
app_name = "Payments"

urlpatterns = [
    #A URL mapped to the 'PaymentHistoryView' that renders a user's payment history.
    path('my_payments/',views.PaymentHistoryView.as_view(), name='my_payments'),
    #A URL mapped to the 'CreateCartOrderView' that creates an order for a user's cart products.
    path('product_cart_order/', views.CreateCartOrderView.as_view(), name='create_cart_order'),
    #A URL mapped to the 'CreateQuickOrderView' that creates an order for a product.
    path('product_quick_order/<pk>/', views.CreateQuickOrderView.as_view(), name='create_quick_order'),
    #A URL mapped to the 'CartPaymentStatusView' that renders the payment status of a cart order.
    path('payment_status/', views.CartPaymentStatusView.as_view(), name='cart_payment_status'),
    #A URL mapped to the 'QuickPaymentStatusView' that renders the payment status of an individual product order.
    path('quick_payment_status/<pk>/', views.QuickPaymentStatusView.as_view(), name='quick_payment_status'),
]

SplendidReads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #The admin site URL.
    path('admin/', admin.site.urls),
    #Includes the 'Products' app URLs.
    path('',include('Products.urls')),
    #Includes the 'Accounts' app URLs.
    path('',include('Accounts.urls')),
    #Includes the 'Cart' app URLs.
    path('',include('Cart.urls')),
    #Includes the 'Payments' app URLs.
    path('',include('Payments.urls')),
    #Includes the 'Ebooks' app URLs.
    path('',include('Ebooks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Payments/models.py
from django.conf import settings
from django.db import models

class Payment(models.Model):
    """
    A class that extends Django's default Model class.
    It models the apps payments.

    Attributes
    ----------
    customer : User
        Represents the site's users.
        It is a foreign key to the User model.
    status : str
        Represents a payment status.
    order_id : str
        Represents a unique order ID.
    payment_id : str
        Represents a payment uniquely.
    payment_signature : str
        Used to verify whether a payment is authentic.
    payment_time : str
        Represents the time a payment was done.
    """
    customer =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, default="Payment Failed")
    order_id =  models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100)
    payment_signature = models.CharField(max_length=100)
    payment_time = models.DateTimeField(auto_now_add=True)

Payments/views.py
from Cart.utils import get_cart_products, get_cart_total_amount, remove_cart_products
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.utils.decorators import method_decorator
from Ebooks.utils import add_new_customer_ebook, get_ebook
from Payments.models import Payment
from Payments.utils import create_payment, get_customer_payments
from Products.utils import get_product, set_product_sale_count
import random
import razorpay

client = razorpay.Client(auth=("Your KEY ID", "Your KEY SECRET"))

@method_decorator(login_required, name='dispatch')
class CartPaymentStatusView(View):
    """
    A class that extends Django's View class.
    It is used for rendering a user's cart products payment status.

    Methods
    -------
    post(self, request, *args, **kwargs)
        Handles POST requests.

    """
    def post(self, request, *args, **kwargs):
        """
        Renders the payment status page.
        On payment success, a new 'MyEbooks' object is created,'ProductSales' data is updated, a user's cart is emptied.
        All these operations are atomic.

        Parameters
        ----------
        request : HttpRequest
            Contains HttpRequest parameters.
        *args
            Optional unnamed arguments.
        **kwargs
            Optional named arguments.

        Returns
        -------
        Payment status of an order.
        """
        payment_details = {
            'razorpay_payment_id' : request.POST.get('razorpay_payment_id'),
            'razorpay_order_id' : request.POST.get('razorpay_order_id'),
            'razorpay_signature' : request.POST.get('razorpay_signature')
        }
        context = {
            'payment_id' : payment_details['razorpay_payment_id'],
            'order_id' : payment_details['razorpay_order_id'],
        }

        try:
            status = client.utility.verify_payment_signature(payment_details)
            context['status'] = 'Payment Successful'
            payment = create_payment(self.request.user, payment_details['razorpay_order_id'], payment_details['razorpay_payment_id'], payment_details['razorpay_signature'])
            context['payment_time'] = payment.payment_time
            with transaction.atomic():
                existing_cart_products = get_cart_products(self.request.user)
                if existing_cart_products is not None:
                    for cart_object in existing_cart_products:
                        ebook = get_ebook(cart_object.product)
                        add_new_customer_ebook(self.request.user, ebook)
                        set_product_sale_count(cart_object.product)
                remove_cart_products(self.request.user)
            payment.status = context['status']
            payment.save()
            return render(request, 'Payments/payment_status.html', context)
        except :
            context['status'] = 'Payment Failed'
            return render(request, 'Payments/payment_status.html', context)


@method_decorator(login_required, name='dispatch')
class CreateCartOrderView(View):
    """
    A class that extends Django's View class.
    It is used to create a cart order.

    Methods
    -------
    post(self, request, *args, **kwargs)
        Handles POST requests.
    """
    def post(self, request, *args, **kwargs):
        """
        Renders the checkout page.
        Creates a order using the Razorpay API.

        Parameters
        ----------
        request : HttpRequest
            Contains HttpRequest parameters.
        *args
            Optional unnamed arguments.
        **kwargs
            Optional named arguments.

        Returns
        -------
        Checkout page if an order is created otherwise, error message.
        """
        existing_cart_products = get_cart_products(self.request.user)
        order_amount = get_cart_total_amount(existing_cart_products)
        order_amount_paise = order_amount * 100
        order_currency = 'INR'
        order_response = client.order.create(dict(amount=order_amount_paise, currency=order_currency))
        order_id = order_response['id']
        order_status = order_response['status']
        context = {}
        if order_status=='created':
            context['amount_paise'] = order_amount_paise
            context['cart'] = existing_cart_products
            context['total_amount'] = order_amount
            context['order_id'] = order_id
            return render(request, 'Payments/checkout_page.html', context)
        return HttpResponse('Error')


@method_decorator(login_required, name='dispatch')
class CreateQuickOrderView(View):
    """
    A class that extends Django's View class.
    It is used to create a quick order.

    Methods
    -------
    post(self, request, *args, **kwargs)
        Handles POST requests.
    """
    def post(self, request, *args, **kwargs):
        """
        Renders the checkout page.
        Creates a order using the Razorpay API.

        Parameters
        ----------
        request : HttpRequest
            Contains HttpRequest parameters.
        *args
            Optional unnamed arguments.
        **kwargs
            Optional named arguments.

        Returns
        -------
        Checkout page if an order is created otherwise, error message.
        """
        product = get_product(kwargs['pk'])
        order_amount = product.Price
        order_amount_paise = order_amount * 100
        order_currency = 'INR'
        order_response = client.order.create(dict(amount=order_amount_paise, currency=order_currency))
        order_id = order_response['id']
        order_status = order_response['status']
        context = {}
        if order_status=='created':
            context['amount_paise'] = order_amount_paise
            context['product'] = product
            context['total_amount'] = order_amount
            context['order_id'] = order_id
            context['pk'] = kwargs['pk']
            return render(request, 'Payments/checkout_page.html', context)
        return HttpResponse('<h1>Error</h1>')


@method_decorator(login_required, name='dispatch')
class PaymentHistoryView(TemplateView):
    """
    A class that extends Django's TemplateView class.
    It is used to retrieve a user's payment history.

    Attributes
    ----------
    template_name : str
        Specifies the template to render.

    Methods
    -------
    get_context_data(self, **kwargs)
        Handles GET requests.
    """
    template_name = 'Payments/payment_history_page.html'

    def get_context_data(self, **kwargs):
        """
        Renders the customer's payment history page.

        Parameters
        ----------
        **kwargs
            Optional named arguments.

        Returns
        -------
        A customer's payment history.
        """
        context = super(PaymentHistoryView, self).get_context_data(**kwargs)
        context['payments'] = get_customer_payments(self.request.user)
        return context


@method_decorator(login_required, name='dispatch')
class QuickPaymentStatusView(View):
    """
    A class that extends Django's View class.
    It is used to retrieve a user's payment history.

    Attributes
    ----------
    template_name : str
        Specifies the template to render.

    Methods
    -------
    post(self, request, *args, **kwargs)
        Handles POST requests.
    """
    def post(self, request, *args, **kwargs):
        """
        Renders the payment status page.
        On payment success, a new 'MyEbooks' object is created,'ProductSales' data is updated.
        All these operations are atomic.

        Parameters
        ----------
        request : HttpRequest
            Contains HttpRequest parameters.
        *args
            Optional unnamed arguments.
        **kwargs
            Optional named arguments.

        Returns
        -------
        Payment status of an order.
        """
        payment_details = {
            'razorpay_payment_id' : request.POST.get('razorpay_payment_id'),
            'razorpay_order_id' : request.POST.get('razorpay_order_id'),
            'razorpay_signature' : request.POST.get('razorpay_signature')
        }
        context = {
            'payment_id' : payment_details['razorpay_payment_id'],
            'order_id' : payment_details['razorpay_order_id'],
        }

        try:
            status = client.utility.verify_payment_signature(payment_details)
            context['status'] = 'Payment Successful'
            payment = create_payment(self.request.user, payment_details['razorpay_order_id'], payment_details['razorpay_payment_id'], payment_details['razorpay_signature'])
            context['payment_time'] = payment.payment_time
            with transaction.atomic():
                product = get_product(kwargs['pk'])
                ebook = get_ebook(product)
                add_new_customer_ebook(self.request.user, ebook)
                set_product_sale_count(product)
            payment.status = context['status']
            payment.save()
            return render(request, 'Payments/payment_status.html', context)
        except:
            context['status'] = 'Payment Failure'
            return render(request, 'Payments/payment_status.html', context)

Payments/templates/Payments/checkout_page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">SKU</th>
                            <th scope="col">Title</th>
                            <th scope="col">Author</th>
                            <th scope="col">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if cart %}
                            {% for item in cart %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{item.product.SKU}}</td>
                                    <td>{{item.product.Title}}</td>
                                    <td>{{item.product.Author}}</td>
                                    <td>₹{{item.product.Price}}</td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <th scope="row">1</th>
                                <td>{{product.SKU}}</td>
                                <td>{{product.Title}}</td>
                                <td>{{product.Author}}</td>
                                <td>₹{{product.Price}}</td>
                            </tr>
                        {% endif %}
                        <tr>
                          <th colspan="4"scope="row">Total</th>
                          <td><strong>₹{{total_amount}}</strong</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row justify-content-end">
            <form action="{% if cart %}{% url 'Payments:cart_payment_status'%}{% else %}{% url 'Payments:quick_payment_status' pk=pk %}{% endif %}" method="POST">
            {% csrf_token %}
                <script
                    src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key="Your API key" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                    data-amount="{{amount_paise}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                    data-order_id="{{order_id}}"//Replace with the order_id generated by you in the backend.
                    data-buttontext="Pay with Razorpay"
                    data-name="SplendidReads"
                    data-prefill.name="{{request.user.get_full_name}}"
                    data-prefill.email="{{request.user.email}}"
                    data-theme.color="#FB8122">
                </script>
                <input type="hidden" custom="Hidden Element" name="hidden">
            </form>
        </div>
    </div>
{% endblock %}

Payments/templates/Payments/payment_history_page.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-3">
            <h2>My Payments</h2>
        </div>
        <div class="row justify-content-center mt-2">
            <div class="accordion" id="accordionExample">
                {% for payment in payments %}
                    <div class="card">
                        <div class="card-header" id="heading{{forloop.counter}}">
                            <h2 class="mb-0">
                                <button class="btn btn-orange btn-block " type="button" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="false" aria-controls="collapse{{forloop.counter}}">
                                    {{payment.payment_id}}
                                </button>
                            </h2>
                        </div>
                        <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="heading{{forloop.counter}}" data-parent="#accordionExample">
                            <div class="card-body">
                                <p><strong>Customer Name : </strong>{{ payment.customer.get_full_name }}</p>
                                <p><strong>Customer ID : </strong>{{payment.customer.get_username}}</p>
                                <p><strong>Payment Status : </strong>{{payment.status}}</p>
                                <p><strong>Order ID : </strong>{{payment.order_id}}</p>
                                <p><strong>Payment ID : </strong>{{payment.payment_id}}</p>
                                <p><strong>Payment Time : </strong>{{payment.payment_time}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

Payments/templates/Payments/payment_status.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-3">
            <div class="card">
                <div class="card-header">
                    <h2 class = "text-center">Payment Details</h2>
                </div>
                <div class="card-body">
                    <p><strong>Customer Name : </strong>{{ request.user.get_full_name }}</p>
                    <p><strong>Customer ID : </strong>{{request.user.get_username}}</p>
                    <p><strong>Payment Status : </strong>{{status}}</p>
                    <p><strong>Payment ID : </strong>{{payment_id}}</p>
                    <p><strong>Order ID : </strong>{{order_id}}</p>
                    <p><strong>Payment Time : </strong>{{payment_time}}</p>
                    <div class="row justify-content-center">
                        <a href="{% url 'Ebooks:my_ebooks' %}" class="btn btn-orange" role="button">Read Ebook</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}