Accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from Accounts.forms import SignInForm, ForgotPasswordForm, NewPasswordForm, ChangePasswordForm
from django.urls import reverse_lazy

#Namespace for the Accounts app.
app_name = 'Accounts'

urlpatterns = [
    #A url mapped to a view that generates an email confirmation request.
    path('email_confirmation/<uidb64>/<token>/',views.email_confirmation, name='email_confirmation'),
    #A url mapped to a view that renders the user's my account page.
    path('myaccount/', views.myaccount, name = 'myaccount'),
    #A url mapped to a view that renders a password change page for signed in users.
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='Accounts/password_change_form.html', form_class=ChangePasswordForm, success_url=reverse_lazy('Accounts:password_change_done')), name='password_change'),
    #A url mapped to a view that generates a response when a signed in user changes their password.
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='Accounts/password_change_done.html'), name='password_change_done'),
    #A url mapped to a view that renders the reset password page.
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='Accounts/password_reset.html', success_url=reverse_lazy('Accounts:password_reset_done'),form_class=ForgotPasswordForm, email_template_name='Accounts/password_reset_email.html', subject_template_name='Accounts/password_reset_subject.txt'), name='password_reset'),
    #A url mapped to a view that renders a response on a user's request to reset their password on the reset password page.
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Accounts/password_reset_done.html'), name='password_reset_done'),
    #A url mapped to a view that generates a reset password link that is emailed to the user's email address.
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Accounts/password_reset_confirm.html", form_class=NewPasswordForm, success_url=reverse_lazy('Accounts:password_reset_complete')), name='password_reset_confirm'),
    #A url mapped to a view that renders a message when the user opens the reset password link.
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='Accounts/password_reset_complete.html'), name='password_reset_complete'),
    #A url mapped to a view that renders the signin page.
    path('signin/', auth_views.LoginView.as_view(template_name='Accounts/signin.html', authentication_form=SignInForm, redirect_field_name="Notes/my_diaries.html"), name = 'login'),
    #A url mapped to a view that handles a user signout.
    path('signout/', auth_views.LogoutView.as_view(), name = 'logout'),
    #A url mapped to a view that renders the signup page.
    path('signup/', views.signup, name = 'signup'),
    #A url mapped to a view that renders a response when a user confirms their email address.
    path('signup/complete/',views.SignUpCompleteView.as_view(), name='signup_complete'),
    #A url mapped to a view that renders a response when a user signs up.
    path('signup/done/',views.SignUpDoneView.as_view(), name='signup_done'),
    #A url mapped to a view that renders a forgot username page.
    path('username_send/', views.send_username, name='send_username'),
    #A url mapped to a view that renders a response when a user's username is emailed to their email address.
    path('username_send_done/',views.SendUsernameDoneView.as_view(), name='send_username_done'),
]

Cart/urls.py
from Cart import views
from django.urls import path

#Namespace for the Cart app.
app_name = "Cart"

urlpatterns = [
    #A URL mapped to CartPageView view that renders a user's cart on the cart page.
    path('cart/', views.CartPageView.as_view(), name='cart_page'),
    #A URL mapped to CartAddView view that adds a product to a user's cart.
    path('cart/add/<pk>/', views.CartAddView.as_view(), name='add_to_cart'),
    #A URL mapped to CartRemoveView view that removes a product from a user's cart.
    path('cart/remove/<pk>', views.CartRemoveView.as_view(), name='remove_from_cart'),
]

Ebooks/urls.py
from django.urls import path
from Ebooks import views

#Namespace for the Ebooks app.
app_name = "Ebooks"

urlpatterns = [
    #A URL mapped to the MyEbooksView that renders a user's ebooks.
    path('myebooks/', views.MyEbooksView.as_view(), name='my_ebooks'),
]

Payments/urls.py
from django.urls import path
from Payments import views

#Namespace for the 'Payments' app.
app_name = "Payments"

urlpatterns = [
    #A URL mapped to the 'PaymentHistoryView' that renders a user's payment history.
    path('my_payments/',views.PaymentHistoryView.as_view(), name='my_payments'),
    #A URL mapped to the 'CreateCartOrderView' that creates an order for a user's cart products.
    path('product_cart_order/', views.CreateCartOrderView.as_view(), name='create_cart_order'),
    #A URL mapped to the 'CreateQuickOrderView' that creates an order for a product.
    path('product_quick_order/<pk>/', views.CreateQuickOrderView.as_view(), name='create_quick_order'),
    #A URL mapped to the 'CartPaymentStatusView' that renders the payment status of a cart order.
    path('payment_status/', views.CartPaymentStatusView.as_view(), name='cart_payment_status'),
    #A URL mapped to the 'QuickPaymentStatusView' that renders the payment status of an individual product order.
    path('quick_payment_status/<pk>/', views.QuickPaymentStatusView.as_view(), name='quick_payment_status'),
]

Products/urls.py
from django.urls import path, include
from Products  import views

#Namespace for the 'Products' app.
app_name = "Products"

urlpatterns = [
    #A URL mapped to the 'HomePageView' that renders the home page.
    path('',views.HomePageView.as_view(), name='home_page'),
    #A URL mapped to the 'GenrePageView' that renders the genre page.
    path('genres/',views.GenrePageView.as_view(), name='genres'),
    #A URL mapped to the 'ViewAllView' that renders all products of a selected type.
    path('products/<product_filter>/', views.ViewAllView.as_view(), name='product_filter'),
    #A URL mapped to the 'ProductsView' that renders products of a specific genre.
    path('products/<genre>',views.ProductsView.as_view(), name='products'),
    #A URL mapped to the 'ProductPageView' that renders a product's details.
    path('product_page/<pk>/', views.ProductPageView.as_view(), name='product_page'),
    #A URL mapped to the 'RatingsPageView' that renders a product's ratings.
    path('product_reviews/<pk>/', views.RatingsPageView.as_view(), name='all_product_ratings'),
    #A URL mapped to the 'AutoCompleteView' that is used for autocompletion in the search bar.
    path('search_products_autocomplete/', views.AutoCompleteView.as_view(), name='search_products_autocomplete'),
    #A URL mapped to the 'ProductSearchView' that renders search results.
    path('search_products', views.ProductSearchView.as_view(), name='search_products'),
]

SplendidReads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #The admin site URL.
    path('admin/', admin.site.urls),
    #Includes the 'Products' app URLs.
    path('',include('Products.urls')),
    #Includes the 'Accounts' app URLs.
    path('',include('Accounts.urls')),
    #Includes the 'Cart' app URLs.
    path('',include('Cart.urls')),
    #Includes the 'Payments' app URLs.
    path('',include('Payments.urls')),
    #Includes the 'Ebooks' app URLs.
    path('',include('Ebooks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SplendidReads</title>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="shortcut icon"  href="{% static 'images/logo.ico' %}">
        <link rel = "stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div id="page-container">
            <div id="content-wrap">
                <nav class = "navbar navbar-expand-lg navbar-custom">
                    <a class = "navbar-brand" href = "{% url 'Products:home_page' %}"><img src = "{% static 'images/logo.png' %}" height = "50px" width = "50px"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span  role="button" ><i class="fa fa-bars" aria-hidden="true"></i></span>
                    </button>
                    <div class = "collapse navbar-collapse justify-content-end" id = "navbarToggle">
                        <ul class = "navbar-nav">
                            <li class = "nav-item">
                                <a class = "nav-link" href = "{% url 'Products:home_page' %}">Home <i class="fas fa-home fa-lg"></i></a>
                            </li>
                            <li class = "nav-item">
                                <a class = "nav-link" href = "{% url 'Products:genres' %}">Genres <i class="fas fa-layer-group fa-lg"></i></a>
                            </li>
                            {% if not user.is_authenticated %}
                                <li class = "nav-item">
                                    <a class = "nav-link" href = "{% url 'Accounts:signup' %}">Sign Up <i class="fas fa-user-plus fa-lg"></i></a>
                                </li>
                                <li class = "nav-item">
                                    <a class = "nav-link" href = "{% url 'Accounts:login' %}">Sign In <i class="fas fa-sign-in-alt fa-lg"></i></a>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li class = "nav-item">
                                    <a class = "nav-link" href="{% url 'Cart:cart_page' %}">Cart <i class="fas fa-shopping-cart fa-lg"></i></a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Hi {{request.user.first_name}} <i class="fas fa-user-circle fa-lg"></i>
                                    </a>
                                    <div class="dropdown-menu bg-orange" aria-labelledby="navbarDropdown">
                                      <a class = "dropdown-item" href="{% url 'Accounts:myaccount' %}">My Account <i class="fas fa-user-circle fa-lg"></i></a>
                                      <a class = "dropdown-item" href="{% url 'Ebooks:my_ebooks' %}">My E-books <i class="fas fa-book fa-lg"></i></a>
                                      <a class = "dropdown-item" href="{% url 'Payments:my_payments' %}">My Payments <i class="fas fa-receipt fa-lg"></i></a>
                                      <a class = "dropdown-item" href="{% url 'Accounts:logout' %}">Sign Out <i class="fas fa-sign-out-alt fa-lg"></i></a>
                                    </div>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
                {% block content %}
                {% endblock %}
                </div>
            <footer id="footer">
                <div class="container mt-3">
                    <small>&#169; 2020 SplendidReads</small>
                </div>
            </footer>
            </div>
            <script>
                $( function() {
                  $( "#search" ).autocomplete({
                    source: "{% url 'Products:search_products_autocomplete' %}",
                    select : function(event, ui){
                      window.location.href = "{% url 'Products:product_page' pk=0 %}".replace('0',ui.item.value);
                    }
                  });
                } );
            </script>
            <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
            <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </body>
</html>