Cart/urls.py
from Cart import views
from django.urls import path

#Namespace for the Cart app.
app_name = "Cart"

urlpatterns = [
    #A URL mapped to CartPageView view that renders a user's cart on the cart page.
    path('cart/', views.CartPageView.as_view(), name='cart_page'),
    #A URL mapped to CartAddView view that adds a product to a user's cart.
    path('cart/add/<pk>/', views.CartAddView.as_view(), name='add_to_cart'),
    #A URL mapped to CartRemoveView view that removes a product from a user's cart.
    path('cart/remove/<pk>', views.CartRemoveView.as_view(), name='remove_from_cart'),
]

Payments/urls.py
from django.urls import path
from Payments import views

#Namespace for the 'Payments' app.
app_name = "Payments"

urlpatterns = [
    #A URL mapped to the 'PaymentHistoryView' that renders a user's payment history.
    path('my_payments/',views.PaymentHistoryView.as_view(), name='my_payments'),
    #A URL mapped to the 'CreateCartOrderView' that creates an order for a user's cart products.
    path('product_cart_order/', views.CreateCartOrderView.as_view(), name='create_cart_order'),
    #A URL mapped to the 'CreateQuickOrderView' that creates an order for a product.
    path('product_quick_order/<pk>/', views.CreateQuickOrderView.as_view(), name='create_quick_order'),
    #A URL mapped to the 'CartPaymentStatusView' that renders the payment status of a cart order.
    path('payment_status/', views.CartPaymentStatusView.as_view(), name='cart_payment_status'),
    #A URL mapped to the 'QuickPaymentStatusView' that renders the payment status of an individual product order.
    path('quick_payment_status/<pk>/', views.QuickPaymentStatusView.as_view(), name='quick_payment_status'),
]

Products/urls.py
from django.urls import path, include
from Products  import views

#Namespace for the 'Products' app.
app_name = "Products"

urlpatterns = [
    #A URL mapped to the 'HomePageView' that renders the home page.
    path('',views.HomePageView.as_view(), name='home_page'),
    #A URL mapped to the 'GenrePageView' that renders the genre page.
    path('genres/',views.GenrePageView.as_view(), name='genres'),
    #A URL mapped to the 'ViewAllView' that renders all products of a selected type.
    path('products/<product_filter>/', views.ViewAllView.as_view(), name='product_filter'),
    #A URL mapped to the 'ProductsView' that renders products of a specific genre.
    path('products/<genre>',views.ProductsView.as_view(), name='products'),
    #A URL mapped to the 'ProductPageView' that renders a product's details.
    path('product_page/<pk>/', views.ProductPageView.as_view(), name='product_page'),
    #A URL mapped to the 'RatingsPageView' that renders a product's ratings.
    path('product_reviews/<pk>/', views.RatingsPageView.as_view(), name='all_product_ratings'),
    #A URL mapped to the 'AutoCompleteView' that is used for autocompletion in the search bar.
    path('search_products_autocomplete/', views.AutoCompleteView.as_view(), name='search_products_autocomplete'),
    #A URL mapped to the 'ProductSearchView' that renders search results.
    path('search_products', views.ProductSearchView.as_view(), name='search_products'),
]

SplendidReads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #The admin site URL.
    path('admin/', admin.site.urls),
    #Includes the 'Products' app URLs.
    path('',include('Products.urls')),
    #Includes the 'Accounts' app URLs.
    path('',include('Accounts.urls')),
    #Includes the 'Cart' app URLs.
    path('',include('Cart.urls')),
    #Includes the 'Payments' app URLs.
    path('',include('Payments.urls')),
    #Includes the 'Ebooks' app URLs.
    path('',include('Ebooks.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/forms.py
from django import forms
from django.forms import ModelForm
from Products.filters import Filters
from Products.models import ProductReviews

class ProductFilter(forms.Form):
    """
    A class that extends Django's default Form class.
    This class is used for creating a form used as a product filter.

    Attributes
    ----------
    FILTER_CHOICES : list
        A list of 2-tuples that contain the filter choice name in the model and user representation name.
    product_filter
        Represents the product filter.
    """

    FILTER_CHOICES = Filters().get_product_filters()
    product_filter = forms.ChoiceField(choices=FILTER_CHOICES,required=True)

    def __init__(self, *args, **kwargs):
        """
        Overrides the default form widgets for modifying the form field appearance.

        Parameters
        ----------
        *args
            Non key-worded variable number arguments.
        **kwargs : dict
            Variable dictionary arguments.
        """
        super(ProductFilter, self).__init__(*args, **kwargs)

        #Changes the default form widgets appearance of every field in the form class using update()
        self.fields['product_filter'].widget.attrs.update({'class':'form-control','required':'True'})

class RatingForm(ModelForm):
    """
    A class that extends Django's ModelForm.
    It models the product rating form for users.

    Attributes
    ----------
    CHOICES : list
        A list of 2-tuples that contain the filter choice number in the model and user representation name.
    rating : str
        Collects the rating choice of a user.
    """
    CHOICES = [
        ('5','★'),
        ('4','★'),
        ('3','★'),
        ('2','★'),
        ('1','★'),
    ]
    rating = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

    class Meta:
        """
        An inner class that specifies the meta data of the Model class.
        In this case the model's default field configurations have been Overrided.

        Attributes
        ----------
        model : ProductReviews
            Specifies the model related to the form.
        fields : list
            Contains the fields to be rendered in the form.
        """
        model = ProductReviews
        fields = ['rating','comment']

    def __init__(self, *args, **kwargs):
        """
        Overrides the default form widgets for modifying the form field appearance.

        Parameters
        ----------
        *args
            Non key-worded variable number arguments.
        **kwargs : dict
            Variable dictionary arguments.
        """
        super(RatingForm, self).__init__(*args, **kwargs)

        #Changes the default form widgets appearance of every field in the form class using update()
        self.fields['comment'].widget.attrs.update({'class':'form-control', 'rows':'8','placeholder':'Add your comment here'})

Products/views.py
from Cart.utils import get_cart_product
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, View
from django.utils.decorators import method_decorator
from Ebooks.utils import get_customer_ebook, get_ebook, is_purchased
from Products.filters import Filters
from Products.forms import ProductFilter, RatingForm
from Products.models import AvgProductRatings, Product, ProductReviews
from Products.utils import genre_filter, get_all_products, get_all_product_reviews, get_product,get_product_reviews, get_top_rated, is_reviewed
from Products.utils import product_filter,set_avg_product_review, get_best_sellers, search_filter, search_filter_refine
import random

class AutoCompleteView(View):
    """
    A view that extends Django's default View.
    This view is used to render The search bar's autocomplete feature.

    Methods
    -------
    get(self, request, *args, **kwargs)
        Handles GET requests.
    """
    def get(self, request, *args, **kwargs):
        """
        Retrieves products based on search queries.

        Attributes
        ----------
        request : HttpRequest
            A request object.
        *args
            Unnamed variable arguments.
        **kwargs
            Named Variable arguments.

        Returns
        -------
        Returns retrieved products in Json format.
        """
        search_keyword = request.GET.get('term')
        limit = 5
        if search_keyword:
            search_products = search_filter_refine(search_filter(search_keyword, limit))
            search_results = list(search_products)
            return JsonResponse(search_results, safe=False)

class GenrePageView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render the genres page to a user.

    Attributes
    ----------
    template_name : str
        The html page for the user response.

    Methods
    -------
    get_context_data(self, **kwargs)
        Handles GET requests.
    """
    template_name = "Products/genres.html"

    def get_context_data(self,**kwargs):
        """
        Renders the genres on the genre page.

        Parameters
        ----------
        **kwargs
            Variable arguments.

        Returns
        -------
        Returns a dictionary representing the template context.
        """
        context = super(GenrePageView, self).get_context_data(**kwargs)
        genres = Product.objects.values_list('Genre').distinct()
        context['genres'] = genres
        return context

class HomePageView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render the home page to a user.

    Attributes
    ----------
    template_name : str
        The html page for the user response.

    Methods
    -------
    get_context_data(self, **kwargs)
        Handles GET requests.
    """
    template_name = "Products/home.html"

    def get_context_data(self,**kwargs):
        """
        Renders the home page with different products.

        Parameters
        ----------
        **kwargs
            Variable arguments.

        Returns
        -------
        Returns a dictionary representing the template context.
        """
        context = super(HomePageView, self).get_context_data(**kwargs)
        products = get_all_products()
        context['featured'] = random.sample(list(products), 12)
        context['bestsellers'] = get_best_sellers(6)
        context['latest'] = random.sample(list(products), 6)
        context['top_rated'] = get_top_rated(6)
        context['filter_tags'] = Filters().get_filter_model_value()
        return context

class ProductPageView(View):
    """
    A view that extends Django's default View class.
    This view is used to render a product's detail page to a user.

    Attributes
    ----------
    template_name : str
        The html page for the user response.
    form_class : RatingForm
        Represents the rating form class.

    Methods
    -------
    get(self, request, *args, **kwargs)
        Handles GET requests.
    post(self, request, *args, **kwargs)
        Handles POST requests.
    """
    template_name = "Products/product_page.html"
    form_class = RatingForm

    def get(self, request, *args, **kwargs):
        """
        Renders a product's details.

        Parameters
        ----------
        request : HttpRequest
            A request object.
        *args
            Unnamed variable arguments.
        **kwargs
            Named Variable arguments.

        Returns
        -------
        Returns a response with the product page.
        """
        context = kwargs
        limit=5
        product = Product.objects.get(pk=context['pk'])
        filtered_products = genre_filter(product.Genre)
        similar_products = random.sample(list(filtered_products), 6)
        product_reviews = get_product_reviews(product, limit)
        context['product'] = product
        context['similar_products'] = similar_products
        context['product_reviews'] = product_reviews
        context['five_stars'] = range(1,6)
        existing_cart_product = None
        user_ebook = None
        if self.request.user.is_authenticated:
            ebook = get_ebook(product)
            user_ebook = get_customer_ebook(self.request.user, ebook)
            existing_cart_product = get_cart_product(self.request.user, product)
            if is_purchased(self.request.user, ebook):
                if not is_reviewed(self.request.user, product):
                    context['rating_form'] = RatingForm()
        if user_ebook is not None:
            context['user_ebook_exists'] = True
        elif existing_cart_product is None:
            context["add_to_cart"] = True
        else:
            context["add_to_cart"] = False
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Handles product reviews posted by users.

        Parameters
        ----------
        request : HttpRequest
            A POST request with rating form details.
        *args
            Unnamed variable arguments.
        **kwargs
            Named Variable arguments.

        Returns
        -------
        Redirects to product page.
        """
        form = RatingForm(request.POST)
        context = kwargs
        if form.is_valid():
            book_review = form.save(commit=False)
            book_review.customer = self.request.user
            product = Product.objects.get(pk=context['pk'])
            book_review.product = product
            set_avg_product_review(self.request.user, product ,request.POST.get('rating'))
            form.save()
            return redirect('Products:product_page',pk=context['pk'])
        return redirect('Products:product_page',pk=context['pk'])

class ProductsView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render the product catalog page to a user.

    Attributes
    ----------
    template_name : str
        The html page for the user response.

    Methods
    -------
    get_context_data(self, **kwargs)
        Handles GET requests.
    """
    template_name = "Products/product_catalog.html"

    def get_context_data(self, **kwargs):
        """
        Renders products according to genre and the selected filter.

        Parameters
        ----------
        **kwargs
            Variable arguments.

        Returns
        -------
        Returns a dictionary representing the template context.
        """
        context = super(ProductsView, self).get_context_data(**kwargs)
        if self.request.GET.get('product_filter'):
            context['filter_string'] = self.request.GET.get('product_filter')
            context['filter'] = ProductFilter(self.request.GET)
            if len(context['genre']) > 0:
                filtered_products = product_filter(self.request.GET.get("product_filter"),genre=context['genre'])

        else:
            context['filter'] = ProductFilter()
            if len(context['genre']) > 0:
                filtered_products = genre_filter(context['genre'])

        paginator = Paginator(filtered_products, 30)
        page_number = self.request.GET.get('page')
        context['products'] = paginator.get_page(page_number)
        return context

class ProductSearchView(View):
    """
    A view that extends Django's default View class.
    This view is used to render the product catalog page to a user with products that match a user's search.

    Attributes
    ----------
    template_name : str
        The html page for the user response.

    Methods
    -------
    get(self, request, *args, **kwargs)
        Handles GET requests.
    post(self, request, *args, **kwargs)
        Handles POST requests.
    """
    template_name = 'Products/product_catalog.html'

    def get(self, request, *args, **kwargs):
        """
        Renders a list of products That match a search term.

        Parameters
        ----------
        request : HttpRequest
            A request object.
        *args
            Unnamed variable arguments.
        **kwargs
            Named Variable arguments.

        Returns
        -------
        Returns a response with products.
        """
        context = {}
        search_keyword = self.request.GET.get('search_keyword')
        search_results = None
        if search_keyword:
            search_results = search_filter(search_keyword)
        paginator = Paginator(search_results, 30)
        page_number = self.request.GET.get('page')
        context['products'] = paginator.get_page(page_number)
        context['search_keyword'] = search_keyword
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):

Products/templates/Products/all_product_reviews.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row mt-3">
            <div class="col-sm-6">
                <h2>Ratings</h2>
                {% for review in product_reviews %}
                    <div class="row">
                        <div class="col-md-6">
                            {% include 'Products/product_reviews.html' %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

Products/templates/Products/genres.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for genre in genres %}
                <div class="col-sm-4 col-lg-2 col-6 mt-5">
                    <a href="{% url 'Products:products' genre=genre.0 %}">
                        <div class="card justify-content-center h-100">
                          <div class="card-body">
                              <h5 class="card-text">{{genre.0}}</h5>
                          </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Products/templates/Products/home.html
{% extends 'base.html' %}

{% block content %}
    {% include 'Products/product_search.html' %}
    <div class="container-fluid mt-3">
        <div class="row justify-content-center">
            <h3>Featured</h3>
        </div>
        <div class="row">
            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                      <div class="row">
                        {%for product in featured|slice:"0:6" %}
                          {% include 'Products/product_cards.html' %}
                        {% endfor %}
                      </div>
                    </div>
                      <div class="carousel-item">
                        <div class="row">
                          {%for product in featured|slice:"6:12" %}
                          {% include 'Products/product_cards.html' %}
                          {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
              <h3>Latest</h3>
        </div>
        <div class="row">
            {%for product in latest %}
            {% include 'Products/product_cards.html' %}
            {% endfor %}
        </div>
        <div class="row justify-content-end">
            <p><a href="{% url 'Products:product_filter' product_filter=filter_tags.latest %}">View All <i class="fas fa-arrow-circle-right fa-lg"></i></a></p>
        </div>
        <div class="row justify-content-center mt-5">
              <h3>Top Rated</h3>
        </div>
        <div class="row">
            {%for product in top_rated %}
            {% include 'Products/product_cards.html' %}
            {% endfor %}
        </div>
        <div class="row justify-content-end">
            <p><a href="{% url 'Products:product_filter' product_filter=filter_tags.top_rated %}">View All <i class="fas fa-arrow-circle-right fa-lg"></i></a></p>
        </div>
        <div class="row justify-content-center mt-5">
              <h3>Best Sellers</h3>
        </div>
        <div class="row">
            {%for product in bestsellers %}
            {% include 'Products/product_cards.html' %}
            {% endfor %}
        </div>
        <div class="row justify-content-end">
            <p><a href="{% url 'Products:product_filter' product_filter=filter_tags.bestsellers %}">View All <i class="fas fa-arrow-circle-right fa-lg"></i></a></p>
        </div>
    </div>
{% endblock %}

Products/templates/Products/product_cards.html
<div class="col-sm-4 col-lg-2 col-6 mt-2">
    <div class="card border-0 h-100">
        <a class="product-links" href="{% url 'Products:product_page' pk=product.pk %}">
            <img src="{{product.Image_URL}}" class="card-img-top img-fluid" alt="{{product.Title}}">
        </a>
        <div class="card-body card-body-modified .no-spaces">
            <a class="product-links" href="{% url 'Products:product_page' pk=product.pk %}">
                <small class="card-title"><b>{{product.Title|truncatechars:51}}</b></small><br>
            </a>
            <small class="card-text">{{product.Author}}</small><br>
            <h5 class="card-text"><strong>₹{{product.Price}}</strong></h5>
            {% if product.avgproductratings.avg_rating %}
                <h5><span class="badge badge-orange text-white">{{product.avgproductratings.avg_rating}}/5 <span class="fa fa-star"></span></span></h5>
            {% endif %}
        </div>
    </div>
</div>

Products/templates/Products/product_catalog.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        {% include 'Products/product_search.html' %}
        {% if filter %}
            <div class="row justify-content-center mt-3">
                <div class="col-md-6 text-center">
                    <button class="btn btn-orange" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        Filter
                    </button>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            <form class="needs-validation" method="GET" novalidate>
                                <div class="form-group">
                                    {{filter.product_filter}}
                                    <div class="invalid-feedback">
                                        Please choose a filter.
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-orange btn-block">Apply Filter</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if products %}
            <div class="row mt-3">
                {% for product in products %}
                    {% include 'Products/product_cards.html' %}
                {% endfor %}
            </div>
            <div class="row mt-5">
                <div class="col">
                    <div class="pagination justify-content-center">
                        <span class="step-links">
                            {% if products.has_previous %}
                                <a href="?page=1{% if filter_string %}&product_filter={{filter_string}}{% endif %}{% if search_keyword %}&search_keyword={{search_keyword}}{% endif %}">&laquo; first</a>
                                <a href="?page={{ products.previous_page_number }}{% if filter_string %}&product_filter={{filter_string}}{% endif %}{% if search_keyword %}&search_keyword={{search_keyword}}{% endif %}">previous</a>
                            {% endif %}
                            <span class="current">
                                Page {{ products.number }} of {{ products.paginator.num_pages }}.
                            </span>
                            {% if products.has_next %}
                                <a href="?page={{ products.next_page_number }}{% if filter_string %}&product_filter={{filter_string}}{% endif %}{% if search_keyword %}&search_keyword={{search_keyword}}{% endif %}">next</a>
                                <a href="?page={{ products.paginator.num_pages }}{% if filter_string %}&product_filter={{filter_string}}{% endif %}{% if search_keyword %}&search_keyword={{search_keyword}}{% endif %}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="row justify-content-center mt-3">
                <div class="col-md-6">
                    <p>{{message}}</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

Products/templates/Products/product_page.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row mt-4">
            <div class="col-md-6">
                <img src="{{product.Image_URL}}" class="img-fluid" alt="{{product.Title}}">
            </div>
            <div class="col-md-6">
                <h3><strong>{{product.Title}}</strong></h3>
                <p><strong>SKU : </strong> {{product.SKU}}</p>
                <p><strong>Author : </strong> {{product.Author}}</p>
                <p><strong>Genre : </strong><a href="{% url 'Products:products' genre=product.Genre %}">{{product.Genre}}</a></p>
                <p><strong>Price : </strong>&#8377;{{product.Price}}</p>
                <div class="row mt-2">
                    {% if user_ebook_exists %}
                        <div class="col-md-6">
                            <strong>You have already purchased this ebook!!!</strong>
                        </div>
                    {% elif add_to_cart %}
                        <div class="col-md-6 form-group">
                            <a href="{% url 'Cart:add_to_cart' pk=product.pk %}" role="button" class="btn btn-orange btn-block">Add to Cart <i class="fas fa-cart-plus fa-lg"></i></a>
                        </div>
                        <div class="col-md-6 form-group">
                            <form action="{% url 'Payments:create_quick_order' pk=product.pk %}" method="POST">
                            {% csrf_token %}
                              <button class="btn btn-block btn-orange" >Buy Now <i class="fas fa-money-bill-wave fa-lg"></i></button>
                            </form>
                        </div>
                    {% else %}
                        <div class="col-md-6">
                            <strong>This product is already in your cart</strong>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-sm-6">
                <h2>Ratings</h2>
                {% if product_reviews %}
                    {% for review in product_reviews %}
                        <div class="row">
                            <div class="col-md-6">
                                {% include 'Products/product_reviews.html' %}
                            </div>
                        </div>
                    {% endfor %}
                    <a href="{% url 'Products:all_product_ratings' pk=product.pk %}">View all</a>
                {% else %}
                    <p class="text-secondary"><i>This product has not been reviewed.</i></p>
                {% endif %}
                {% if rating_form %}
                    <form class="rating_form needs-validation" action="{% url 'Products:product_page' pk=product.pk %}" method="post" novalidate>
                    {% csrf_token %}
                        <div class="form-group">
                            <h2 class="clasificacion ">
                                {% for item in rating_form.rating %}
                                    {{item.tag}}
                                    <label for="{{item.id_for_label}}">{{item.choice_label}}</label>
                                {% endfor %}
                            </h2>
                            <div class="invalid-feedback">
                                This is required.
                            </div>
                        </div>
                        <div class="form-group">
                            {{rating_form.comment}}
                            <div class="invalid-feedback">
                                This field is required.
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-orange">Submit</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <h2>Similar Products</h2>
                <div class="row">
                    {% for product in similar_products %}
                        {% include 'Products/product_cards.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <script>
        // JavaScript for disabling form submissions if there are invalid fields.
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
        </script>

{% endblock %}

Products/templates/Products/product_search.html
<div class="row justify-content-center mt-2">
    <div class="col-md-6">
        <form class="needs-validation" action="{% url 'Products:search_products' %}" method="POST" novalidate>
        {% csrf_token %}
            <div class="input-group" >
                <input class="form-control" type="text" placeholder="Search" name="search" id="search" required>
                <button class="btn btn-orange" type="submit"><i class="fas fa-search fa-lg"></i></button>
                <div class="invalid-feedback">
                    This field is required.
                </div>
            </div>
        </form>
    </div>
</div>
<script>
// JavaScript for disabling form submissions if there are invalid fields.
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>